language: node_js
node_js:
  - '9'
dist: trusty
sudo: required
github-token: 98e36590042559e929e4b7d2ef5396c6d65e50b9
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --base-href https://steinryan.github.io
